### ISSUE TITLE
Best way to do Shipping fees calculation by Country

### ISSUE THREAD

**Issue by andrewvmail** [fabriziotappero/minicart-plus#1]
Just wondering any tips on calculating the shipping by country?

Thanks!

**Comment by fabriziotappero** [comment]
hi there,
interesting question... I wanted to implement something a bout it but at
the end it was not really needed for me. I guess the best and easy way is:
1 let the guy choose the country where he is via a drop down menu inside
minicart popup window. Save it using cookies.
2) calculate right away (during country selection) the new shipping cost
based on some coefficient like "country_coef1" and "country_coef2"

shipping_cost=shipping_fee_base_country_coef1+(shipping_weight_g/1E3)_shipping_fee_per_kg*country_coef2

you will have a two coefficients for each country available in some sort of
lookup table.

Implementation is quite easy but will need some time. Let me know if you
are interested.

cheers
Fabrizio

## 

Fabrizio Tappero

**Comment by andrewvmail** [comment]
Hi Thanks for the tips,

I'm actually interested in getting this going so Im going to try to fork the project and try your tips. 

—

**Comment by fabriziotappero** [comment]
Hi Momo,
it sounds great. Let me know how it goes and if you like I would be happy
to help out and integrated the results in my current version.

Cheers
Fabrizio

## 

Fabrizio Tappero

**Comment by fabriziotappero** [comment]
Hi,
thanks for the patch. It sounds great !

I am unable to try it out now, would it be possible to send me a screenshot
or a live example?

cheers
Fabrizio

## 

Fabrizio Tappero

**Comment by andrewvmail** [comment]
Actually wait a bit on that pull request. I think there is a bit of bugs in
there. I'll update you when it's ready!

Cheers

**Comment by andrewvmail** [comment]
Hi F, 
demo below
http://andrewvmail.github.io/minicart-plus/demo.html

**Comment by andrewvmail** [comment]
So it might work a bit different than you mention in your spec earlier today. I don't really need that second weight coefficient multiplied with the items. I just need to add x weight for any number of items. 

Cheers!

**Comment by fabriziotappero** [comment]
Hi,
it looks pretty good... I imagine I would actually change only the fixed
cost of the shipping... how did you find out an estimation of what it costs
to you to send your stuff to different countries?

Also, you might want to add "other" for a country not in the list.

'd like to include the patch. Would you like to submit a patch?
cheers
Fabrizio

## 

Fabrizio Tappero

**Comment by andrewvmail** [comment]
Hi FT,

Actually what I am selling is always the same size and fairly small so I
can roughly estimate the cost of the shipping and hardcoded it in.

Good idea, I'll include that other for an option.
I think I already did a pull request, is that what you mean by patch?
I'll add that other selection and let you know.

Cheers
AT

**Comment by fabriziotappero** [comment]
hi,
yep thats right, a pull request. I was wondering if you can generate one as
soon as you know that everything is fine.... I notice some placement
problem in IE on Windoz. Do you have a Window machine?

cheers
Fabrizio

## 

Fabrizio Tappero

**Comment by andrewvmail** [comment]
Pull request is already generated do you see it in Github admin ... I got
no Windows machine just Mac, but I might be able to use one at work
tomorrow though. Sure I'll let you know once everything is fine.

AT

**Comment by fabriziotappero** [comment]
Yes, I do see it, I just imagine that you might have to generate a new one
if you make further improvements to your code. Well anyways I am in no
hurry.

cheers
Fabrizio

## 

Fabrizio Tappero

**Comment by andrewvmail** [comment]
Will let you know on that if I need to generate a new PR. From the looks of
it yesterday when I keep committing, it actually just stacks the change on
the same PR.

Cheers
AT

**Comment by andrewvmail** [comment]
HI Fabrizio,

I added the shipping type other. And looks like the changes keeps getting tacked on to the original pull request i made. So I think you can just merge that. Let me know how it goes :)
![comparing_fabriziotappero_gh-pages___andrewvmail_gh-pages_ _fabriziotappero_minicart-plus](https://cloud.githubusercontent.com/assets/2431354/9216919/9fa26944-4075-11e5-8ca2-75b0d6fd42cc.jpg)

**Comment by fabriziotappero** [comment]
Hi,
do you still have this problem?

cheers
Fabrizio

**Comment by andrewvmail** [comment]
No. Its for an older project I did a while back ago. Cheers
